title: Mice to Machines: Neural Representations from
Visual Cortex for Domain Generalization
description: Lessons from Mouse Visual Cortex
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
