---
title: NeuRN: Neuro-inspired Domain Generalization for Image Classification
description: #"Ahmed Qazi*, Hamd Jalil*, Asim Iqbal†*"
note1: "* indicates equal contribution."
note2: "† indicates corresponding author."
show_downloads: true
#google_analytics:
theme: jekyll-theme-cayman
---
